package/linux-tools: fix library search path for cpupower
To avoid problems at link time, we need to search the current directory
(build/linux-custom/tools/power/cpupower/) first for shared libraries
before looking in target/usr/lib.

The search order can make a difference for incremental builds if the
kernel version is switched in between builds. Since libcpupower.so is
installed into target/usr/lib, looking there first could mean that the
build would end up using a mismatched libcpupower (e.g. from a previous
build with an older kernel version).

An error that might be observed would look like this:

[...]/ld: ./utils/cpufreq-info.o: in function `get_boost_mode':
cpufreq-info.c:(.text+0x610): undefined reference to `cpufreq_get_boost_frequencies'
collect2: error: ld returned 1 exit status

Since the proper verson of libcpupower is readily available in our
current working directory, we can resolve the issue by looking there
first. We still need to keep target/usr/lib in our search path, because
cpupower also needs libpci.

refs #SWLINUX-6160

Signed-off-by: Markus Mayer <mmayer@broadcom.com>