toolchain/toolchain-wrapper: handle LLVM and RELRO
Prevent compilation errors of the form

clang-10: error: -Wl,-z,now: 'linker' input unused [-Werror,-Wunused-command-line-argument]
clang-10: error: -Wl,-z,relro: 'linker' input unused [-Werror,-Wunused-command-line-argument]

that are merely caused by passing linker arguments to the compiler when
no linking is being done.

refs #SWLINUX-5885

Signed-off-by: Markus Mayer <mmayer@broadcom.com>